PROJECT/07_database/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('<int:movie_pk>/scores/<int:score_pk>/delete/', views.scores_delete, name='scores_delete'),
    path('<int:movie_pk>/scores/new/', views.scores_create, name='scores_create'),
    path('<int:movie_pk>/edit/', views.edit, name='edit'),
    path('<int:movie_pk>/delete/', views.delete, name='delete'),
    path('<int:movie_pk>/', views.detail, name='detail'),
    path('', views.index, name='index'),
]

PROJECT/07_database/movies/models.py
from django.db import models

# Create your models here.
class Genre(models.Model):
    name = models.CharField(max_length=20)
    
    def __str__(self):
        return self.name

class Movie(models.Model):
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    title = models.CharField(max_length=30)
    audience = models.IntegerField()
    poster_url = models.TextField()
    description = models.TextField()

    def __str__(self):
        return self.title

class Score(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    content = models.CharField(max_length=140)
    score = models.IntegerField()

    def __str__(self):
        return self.content

PROJECT/07_database/movies/views.py
from django.shortcuts import render, redirect
from django.db.models import Avg
from .models import Movie, Genre, Score

# Create your views here.
def index(request):
    # movies = Movie.objects.order_by('-pk')
    movies = Movie.objects.annotate(score_avg=Avg('score__score')).all()
    context = {
        'movies': movies,
    }
    return render(request, 'movies/index.html', context)

def detail(request, movie_pk):
    # movie = Movie.objects.get(pk=movie_pk)
    movie = Movie.objects.annotate(score_avg=Avg('score__score')).get(pk=movie_pk)
    scores = movie.score_set.all()
    genre = Genre.objects.get(pk=movie.genre_id)
    context = {
        'movie': movie,
        'genre': genre,
        'scores': scores,
    }
    return render(request, 'movies/detail.html', context)

def delete(request, movie_pk):
    movie = Movie.objects.get(pk=movie_pk)
    if request.method == 'POST':
        movie.delete()
        return redirect('movies:index')
    else:
        return redirect('movies:detail', movie_pk)

# 추가 사항(영화 정보 수정)
def edit(request, movie_pk):
    movie = Movie.objects.get(pk=movie_pk)
    if request.method == 'POST':
        movie.title = request.POST.get('title')
        movie.audience = request.POST.get('audience')
        movie.poster_url = request.POST.get('poster_url')
        movie.description = request.POST.get('description')
        movie.genre_id = request.POST.get('genre')
        movie.save()
        return redirect('movies:detail', movie_pk)
    else:
        genres = Genre.objects.all()
        context = {
            'movie': movie,
            'genres': genres,
        }
        return render(request, 'movies/edit.html', context)

def scores_create(request, movie_pk):
    movie = Movie.objects.get(pk=movie_pk)
    if request.method == 'POST':
        score = request.POST.get('score')
        content = request.POST.get('content')
        score = Score(movie=movie, score=score, content=content)
        score.save()
    return redirect('movies:detail', movie_pk)


def scores_delete(request, movie_pk, score_pk):
    score = Score.objects.get(pk=score_pk)
    if request.method == 'POST':
        score.delete()
    return redirect('movies:detail', movie_pk)

PROJECT/07_database/movies/templates/movies/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
    <div class="container">
        {% block body %}
        {% endblock  %}
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

PROJECT/07_database/movies/templates/movies/detail.html
{% extends 'movies/base.html' %}
{% block body %}
    <h1>영화 정보 조회</h1>
    <hr>
    <h2>{{ movie.title }}</h2>
    <h3>관객수 : {{ movie.audience }}</h3>
    <h4>종합 평점 : {{ movie.score_avg }}</h4>
    <p><img src="{{ movie.poster_url }}" alt="poster"></p>
    <p>{{ movie.description }}</p>
    <p>{{ genre }}</p>
    {% comment %} <p>{{ movie.genre }}</p> {% endcomment %}
    {% comment %} <p>{{ genre.name }}</p> {% endcomment %}
    <a href="{% url 'movies:index' %}">[목록]</a>
    <a href="{% url 'movies:edit' movie.pk %}">[수정]</a>
    <form action="{% url 'movies:delete' movie.pk %}" method="POST" onsubmit="return confirm('R U SURE??');" style="display: inline">
        {% csrf_token %}
        <input type="submit" value="삭제">
    </form>

    <hr>

    <p>관객 평점 / {{ scores | length }} 개의 평점이 있습니다.</p>
    {% for score in scores %}
        <li>
            한줄평 : {{ score.content }} / {{ score.score }} 점
            <form action="{% url 'movies:scores_delete' movie.pk score.pk %}" method="post" onsubmit="return confirm('R U SURE??');" style="display: inline">
                {% csrf_token %}
                <input type="submit" value="삭제">
            </form>
        </li>
    {% empty %}
        <p><b>평점이 없습니다 ..</b></p>
    {% endfor %}

    <hr>

    <p>평점 등록</p>
    <form action="{% url 'movies:scores_create' movie.pk %}" method="POST">
        {% csrf_token %}
        <label for="score">평점</label>
        <input type="number" name="score" id="score" min="0" max="5" step="1">
        <label for="content">한줄평</label>
        <input type="text" name="content" id="content">
        <input type="submit" value="등록">
    </form>
{% endblock  %}

PROJECT/07_database/movies/templates/movies/edit.html
{% extends 'movies/base.html' %}
{% block body %}
    <h1>영화 정보 수정</h1>
    <hr>
    <form method="POST">
        {% csrf_token %}
        <p><input type="text" name="title" value="{{movie.title}}"></p>
        <p><input type="number" name="audience" value="{{movie.audience}}"></p>
        <p><textarea name="poster_url" cols="30" rows="10">{{movie.poster_url}}</textarea></p>
        <p><textarea name="description" cols="30" rows="10">{{movie.description}}</textarea></p>
        <p>
            <select name="genre">
                {% for genre in genres %}
                    {% if genre.pk == movie.genre.pk %}
                        <option value="{{genre.pk}}" selected>{{genre.name}}</option>
                    {% else %}
                        <option value="{{genre.pk}}">{{genre.name}}</option>
                    {% endif %}
                {% endfor %}
            </select>
        </p>
        <input type="submit" value="수정">
    </form>
    <a href="{% url 'movies:detail' movie.pk %}">[뒤로]</a>
{% endblock  %}

PROJECT/07_database/movies/templates/movies/index.html
{% extends 'movies/base.html' %}
{% block body %}
    <h1>영화 목록</h1>
    <hr>
    {% for movie in movies %}
        <a href="{% url 'movies:detail' movie.pk %}">{{ movie.title }}</a><br>
        <p>종합 평점 : {{ movie.score_avg }}</p>
        <img src="{{ movie.poster_url }}" alt="poster">
        <hr>
    {% endfor %}
{% endblock  %}