PROJECT/EITHER_PROJECT/eithers/urls.py
from django.urls import path
from . import views

app_name = 'eithers'

urlpatterns = [
    path('random/', views.random, name='random'),
    path('<int:question_pk>/comments/<int:answer_pk>/delete/', views.answers_delete, name='answers_delete'),
    path('<int:question_pk>/comments/', views.answers_create, name='answers_create'),
    path('<int:question_pk>/', views.detail, name='detail'),
    path('new/', views.new, name='new'), # GET(new), POST(create)
    path('', views.index, name='index'),
]

PROJECT/EITHER_PROJECT/eithers/models.py
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from django.db import models

# Create your models here.
class Question(models.Model):
    title = models.CharField(max_length=100)
    issue_a = models.CharField(max_length=100)
    issue_b = models.CharField(max_length=100)
    image_a = ProcessedImageField(
            blank=True,
            upload_to='eithers/images',							# 저장 위치
            processors=[ResizeToFill(250,300)],		# 처리할 작업 목록
            format='JPEG',													# 저장 포맷
            options={'quality': 90},								# 옵션
            )
    image_b = ProcessedImageField(
            blank=True,
            upload_to='eithers/images',							# 저장 위치
            processors=[ResizeToFill(250,300)],		# 처리할 작업 목록
            format='JPEG',													# 저장 포맷
            options={'quality': 90},								# 옵션
            )
    def __str__(self):
        return self.title

class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    pick = models.IntegerField()
    comment = models.CharField(max_length=100)

    def __str__(self):
        return self.comment
    

PROJECT/EITHER_PROJECT/eithers/views.py
from django.shortcuts import render, redirect
from .models import Question, Answer
from django.db.models import Q, Count

# Create your views here.
def index(request):
    questions = Question.objects.order_by('-pk')
    # questions = Question.objects.prefetch_related('answer_set').order_by('-pk')
    context = {
        'questions': questions,
    }
    return render(request, 'eithers/index.html', context)

def new(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        issue_a = request.POST.get('issue_a')
        issue_b = request.POST.get('issue_b')
        image_a = request.FILES.get('image_a')
        image_b = request.FILES.get('image_b')

        question = Question(title=title, issue_a=issue_a, issue_b=issue_b, image_a=image_a, image_b=image_b)
        question.save()

        return redirect('eithers:index')
    else:
        return render(request, 'eithers/new.html')

def detail(request, question_pk):
    # 1
    # question = Question.objects.get(pk=question_pk)
    # question = Question.objects.prefetch_related('answer_set').get(pk=question_pk)
    # count_a = len(question.answer_set.filter(pick=0))
    # count_b = len(question.answer_set.filter(pick=1))
    
    # sum_ab = count_a + count_b

    # if sum_ab == 0:
    #     a_per = 0
    #     b_per = 0
    # else:
    #     a_per = round(count_a / sum_ab * 100, 2)
    #     b_per = round(count_b / sum_ab * 100, 2)
    
    # context = {
    #     'question': question, 
    #     'a_per': a_per, 
    #     'b_per': b_per,
    # }

    # 2
    # question = Question.objects.prefetch_related('answer_set').get(pk=question_pk)
    question = Question.objects.annotate(
                                sum_ab=Count('answer'),
                                count_a=Count('answer', filter=Q(answer__pick=0)),
                                count_b=Count('answer', filter=Q(answer__pick=1))
                            ).get(pk=question_pk)

    a_per = round(question.count_a / (question.sum_ab or 1) * 100, 2) or 0
    b_per = round(question.count_b / (question.sum_ab or 1) * 100, 2) or 0
    
    context = {
        'question': question, 
        'a_per': a_per, 
        'b_per': b_per,
    }

    return render(request, 'eithers/detail.html', context)

def answers_create(request, question_pk):
    question = Question.objects.get(pk=question_pk)
    pick = int(request.POST.get('pick'))
    comment = request.POST.get('comment')

    answer = Answer(question=question, pick=pick, comment=comment)
    answer.save()

    return redirect('eithers:detail', question_pk)

def answers_delete(request, question_pk, answer_pk):
    answer = Answer.objects.get(pk=answer_pk)
    if request.method == 'POST':
        answer.delete()
    return redirect('eithers:detail', question_pk)

def random(request):
    # 랜덤 정렬
    question = Question.objects.order_by('?')[0]
    count_a = len(question.answer_set.filter(pick=0))
    count_b = len(question.answer_set.filter(pick=1))
    sum_ab = count_a + count_b

    if sum_ab == 0:
        a_per = 0
        b_per = 0
    else:
        a_per = round(count_a / sum_ab * 100, 2)
        b_per = round(count_b / sum_ab * 100, 2)
    
    context = {
        'question': question, 
        'a_per': a_per, 
        'b_per': b_per,
    }

    return render(request, 'eithers/detail.html', context)

PROJECT/EITHER_PROJECT/eithers/templates/eithers/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Either</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'eithers:index' %}">Either</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'eithers:new' %}">새 글</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'eithers:random' %}">랜덤 글</a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="container">
        {% block body %}
        {% endblock %}
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

PROJECT/EITHER_PROJECT/eithers/templates/eithers/detail.html
{% extends 'eithers/base.html' %}
{% block body %}
<style>
    .form-check input[type=radio] {
        display: none;
    }

    .form-check-label {
        height: 100px;
        width: 300px;
        color: white;
        cursor: pointer;
        text-align: center;
        opacity: 0.5;
        line-height: 100px;
        border-radius: 10px;
    }

    .issue_a {
        background-color: #007bff;
    }

    .issue_b {
        background-color: #dc3545;
    }

    .form-check input[type=radio]:checked + .form-check-label{
        opacity: 1;
    }
</style>

    <!-- 투표 주제 -->
    <div class="jumbotron py-4 mb-1">
        <h1 class="display-4 text-center">{{ question.title }}</h1>
        <hr>
        <div class="d-flex justify-content-around align-items-center mb-4 mt-4">
            <div class="card border-primary" style="width: 15rem;">
                <img src="{{ question.image_a.url }}" class="card-img-top" alt="question.image_a">
                <div class="card-body text-primary text-center">
                    <p class="card-text">{{ question.issue_a }}</p>
                </div>
            </div>
            <div class="card">
                <div class="card-body">
                VS
                </div>
            </div>
            <div class="card border-danger" style="width: 15rem;">
                <img src="{{ question.image_b.url }}" class="card-img-top" alt="question.image_b">
                <div class="card-body text-danger text-center">
                    <p class="card-text">{{ question.issue_b }}</p>
                </div>
            </div>
        </div>
        <div class="progress" style="height: 30px;">
          <div class="progress-bar progress-bar-striped" role="progressbar" style="width: {{ a_per }}%" aria-valuenow="15" aria-valuemin="0" aria-valuemax="100">{{ a_per }} %</div>
          <div class="progress-bar progress-bar-striped bg-danger" role="progressbar" style="width: {{ b_per }}%" aria-valuenow="30" aria-valuemin="0" aria-valuemax="100">{{ b_per }} %</div>
        </div>
    </div>  
    
    <hr>
    
    <!-- 댓글 작성 -->
    <form action="{% url 'eithers:answers_create' question.pk %}" method="POST">
        {% csrf_token %}
        <div class="form-group d-flex justify-content-center">
            <div class="form-check form-check-inline">
                <input id="radio_0" class="form-check-input position-static" type="radio" name="pick" value="0" required>
                <label class="form-check-label issue_a" for="radio_0">{{ question.issue_a }}</label>
            </div>
            <div class="form-check form-check-inline mb-1">
                <input id="radio_1" class="form-check-input position-static" type="radio" name="pick" value="1" required>
                <label class="form-check-label issue_b" for="radio_1">{{ question.issue_b }}</label>
            </div>
        </div>
        <div class="input-group">
            <input type="text" name="comment" class="form-control" aria-label="Text input with checkbox" required>
            <button type="submit" class="btn btn-info">Submit</button>
        </div>

{% comment %} 
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <div class="input-group-text bg-primary">
                    <input type="radio" name="pick" value="0" aria-label="Checkbox for following text input" required>
                </div>
                <div class="input-group-text bg-danger">
                    <input type="radio" name="pick" value="1" aria-label="Checkbox for following text input" required>
                </div>
            </div>
            <input type="text" name="comment" class="form-control" aria-label="Text input with checkbox">
            <button type="submit" class="btn btn-info">Submit</button>
        </div> {% endcomment %}
    </form>

    <hr>

    <!-- 댓글 보여주기 -->
    {% for answer in question.answer_set.all %}
        {% if answer.pick %}
            <h5 class="text-danger">{{ answer.comment }} 
                <form class="d-inline" action="{% url 'eithers:answers_delete' question.pk answer.pk %}" method="POST" onsubmit="return confirm('R U Sure?');">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-dark btn-sm">삭제</button>
                </form>
            </h5>
            <hr>
        {% else %}
            <h5 class="text-primary">{{ answer.comment }} 
                <form class="d-inline" action="{% url 'eithers:answers_delete' question.pk answer.pk %}" method="POST" onsubmit="return confirm('R U Sure?');">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-dark btn-sm">삭제</button>
                </form>
            </h5>
            <hr>
        {% endif %}
    {% endfor %}
{% endblock  %}

PROJECT/EITHER_PROJECT/eithers/templates/eithers/index.html
{% extends 'eithers/base.html' %}
{% block body %}
    {% for question in questions %}
        <div class="jumbotron d-flex justify-content-center mt-3">
            <h1 class="display-4 text-center">{{ question.title }}</h1>
            <a class="btn btn-info btn-lg ml-auto my-auto" href="{% url 'eithers:detail' question.pk %}" role="button">
                <span class="badge badge-light">{{ question.answer_set.all | length }}</span> 개의 의견 보기
            </a>
        </div>
    {% endfor %}
{% endblock  %}

PROJECT/EITHER_PROJECT/eithers/templates/eithers/new.html
{% extends 'eithers/base.html' %}
{% block body %}
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label for="title">질문 주제</label>
            <input type="text" class="form-control" id="title" name="title" placeholder="주제를 선정하세요.">
        </div>
        <div class="form-group">
            <label for="issue_a">이슈_A</label>
            <input type="text" class="form-control" id="issue_a" name="issue_a" placeholder="이슈_a">
        </div>
        <div class="form-group">
            <label for="issue_b">이슈_B</label>
            <input type="text" class="form-control" id="issue_b" name="issue_b" placeholder="이슈_b">
        </div>
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text" id="inputGroupFileAddon01">Upload_A</span>
            </div>
            <div class="custom-file">
                <input type="file" accept="image/*" name="image_a" class="custom-file-input" id="inputGroupFile01" aria-describedby="inputGroupFileAddon01">
                <label class="custom-file-label" for="inputGroupFile01">Choose image_a</label>
            </div>
            <div class="input-group-prepend">
                <span class="input-group-text" id="inputGroupFileAddon01">Upload_B</span>
            </div>
            <div class="custom-file">
                <input type="file" accept="image/*" name="image_b" class="custom-file-input" id="inputGroupFile01" aria-describedby="inputGroupFileAddon02">
                <label class="custom-file-label" for="inputGroupFile01">Choose image_b</label>
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
{% endblock  %}