PROJECT/08_seed/crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('movies/', include('movies.urls')),
    path('admin/', admin.site.urls),
]

PROJECT/08_seed/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('<int:movie_pk>/scores/<int:score_pk>/delete/', views.scores_delete, name='scores_delete'),
    path('<int:movie_pk>/scores/new/', views.scores_create, name='scores_create'),
    path('<int:movie_pk>/delete/', views.delete, name='delete'),
    path('<int:movie_pk>/edit/', views.update, name='update'),
    path('<int:movie_pk>/', views.detail, name='detail'),
    path('new/', views.create, name='create'),
    path('', views.index, name='index'),
]

PROJECT/08_seed/movies/models.py
from django.db import models

# Create your models here.
class Genre(models.Model):
    name = models.CharField(max_length=20)
    def __str__(self):
        return self.name
        
class Movie(models.Model):
    title = models.CharField(max_length=30)
    audience = models.IntegerField()
    poster_url = models.TextField()
    description = models.TextField()
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    def __str__(self):
        return self.title
    
class Score(models.Model):
    content = models.CharField(max_length=140)
    score = models.IntegerField()
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    def __str__(self):
        return self.content

PROJECT/08_seed/movies/forms.py
from django import forms
from .models import Movie, Score

class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = '__all__'

class ScoreForm(forms.ModelForm):
    class Meta:
        model = Score
        fields = ['content', 'score',]
        widgets = {
           'score': forms.NumberInput(attrs={'min': '0', 'max': '5', })}

PROJECT/08_seed/movies/views.py
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404
from django.db.models import Avg
from .models import Genre, Movie, Score
from .forms import MovieForm, ScoreForm

# Create your views here.
def index(request):
    # movies = Movie.objects.annotate(score_avg=Avg('score__score')).all()
    movies = get_list_or_404(Movie.objects.annotate(score_avg=Avg('score__score')))
    context = {'movies':movies}
    return render(request, 'movies/index.html', context)

def create(request):
    if request.method == 'POST':
        form = MovieForm(request.POST)
        if form.is_valid():
            movie = form.save()
            return redirect('movies:detail', movie.pk)
    else:
        form = MovieForm()
    context = {'form': form}
    return render(request, 'movies/form.html', context)

def detail(request, movie_pk):
    # movie = Movie.objects.annotate(score_avg=Avg('score__score')).get(pk=movie_pk)
    movie = get_object_or_404(Movie.objects.annotate(score_avg=Avg('score__score')), pk=movie_pk)
    scores = movie.score_set.all()
    form = ScoreForm()
    context = {'movie': movie, 'scores': scores, 'form': form}

    '''
    # 방법 2
    movie = get_object_or_404(Movie, pk=movie_pk)
    score_avg = movie.score_set.aggregate(Avg('score')).get('score__avg') or 0.0
    scores = movie.score_set.all()
    form = ScoreForm()
    context = {'movie': movie, 'scores': scores, 'score_avg':score_avg, 'form': form}
    '''
    return render(request, 'movies/detail.html', context)

def update(request, movie_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)
    if request.method == 'POST':
        form = MovieForm(request.POST, instance=movie)
        if form.is_valid():
            movie = form.save()
            return redirect('movies:detail', movie.pk)
    else:
        form = MovieForm(instance=movie)
    context = {'form': form}
    return render(request, 'movies/form.html', context)

def delete(request, movie_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)
    if request.method == 'POST':
        movie.delete()
        return redirect('movies:index')
    else:
        return redirect('movies:detail', movie.pk)

def scores_create(request, movie_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)
    if request.method == 'POST':
        '''
        방법 1. 
        form = ScoreForm(request.POST)
        if form.is_valid():
            score = form.save(commit=False)
            score.movie = movie
            score.save()
        '''
        # 방법 2.
        score = Score(movie=movie)
        form = ScoreForm(request.POST, instance=score)
        if form.is_valid():
            score = form.save()
            return redirect('movies:detail', movie.pk)

    return redirect('movies:detail', movie.pk) 

def scores_delete(request, movie_pk, score_pk):
    score = get_object_or_404(Score, pk=score_pk)
    if request.method == 'POST':
    	score.delete()
    return redirect('movies:detail', movie_pk)

PROJECT/08_seed/movies/templates/movies/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
    
   <div class="container">
        {% block body %}
        {% endblock  %}
   </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

PROJECT/08_seed/movies/templates/movies/detail.html
{% extends 'movies/base.html' %}
{% block body %}
{% load crispy_forms_tags %}

<h1>{{ movie.title }}</h1>
<img src="{{ movie.poster_url }}" alt="{{ movie.title }}">
<p>{{ movie.genre }}</p>
<p>{{ movie.description }}</p>
{% if movie.score_avg or movie.score_avg == 0 %}
    <p>종합 {{ movie.score_avg|floatformat:1 }} 점</p>
{% else %}
    <p><b>아직 관람객 평가가 없습니다.</b></p>
{% endif %}
<a href="{% url 'movies:index' %}">BACK</a>
<a href="{% url 'movies:update' movie.pk%}">[수정]</a>
<form action="{% url 'movies:delete' movie.pk %}" method="POST" style="display: inline;">
    {% csrf_token %}
    <input type="submit" value="삭제">
</form>

<hr>

<h4>평점 등록</h4>
<form action="{% url 'movies:scores_create' movie.pk %}" method="POST">
    {% csrf_token %}
    {{ form|crispy }} 
    <input type="submit">
</form>

<hr>

<h4>평점 리스트</h4>
{% for score in scores %}
    <p>Content : {{ score.content }}</p>
    {{ score.score }} 점
    <form action="{% url 'movies:scores_delete' movie.pk score.pk%}" method="POST" style="display: inline;">
        {% csrf_token %}
        <input type="submit" value="삭제">
    </form>
    <hr>
{% endfor %}
{% endblock  %}

PROJECT/08_seed/movies/templates/movies/form.html
{% extends 'movies/base.html' %}
{% block body %}
{% load crispy_forms_tags %}

{% if request.resolver_match.url_name == 'create' %}
    <h1>NEW Movie</h1>
{% else %}
    <h1>EDIT Movie</h1>
{% endif %}

<form method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="submit">
</form>

{% if request.resolver_match.url_name == 'create' %}
    <a href="{% url 'movies:index' %}">BACK</a>
{% else %}
    <a href="{% url 'movies:detail' board.pk %}">BACK</a>
{% endif %}

{% endblock  %}

PROJECT/08_seed/movies/templates/movies/index.html
{% extends 'movies/base.html' %}
{% block body %}
<h1>영화목록</h1>
<a href="{% url 'movies:create' %}">[NEW]</a>
{% for movie in movies %}
    <p><a href="{% url 'movies:detail' movie.pk %}">{{ movie.title }}</a></p>
    {% if movie.score_avg or movie.score_avg == 0 %}
        <p>종합 {{ movie.score_avg|floatformat:1 }} 점</p>
    {% else %}
        <p>아직 평가 없음</p>
    {% endif %}
    <img src="{{ movie.poster_url }}" alt="{{ movie.title }}">
    <hr>
{% endfor %}
{% endblock  %}